server:
  port: 30000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka,http://localhost:2000/eureka
#    register-with-eureka: false
#    fetch-registry: false
spring:
  application:
    name: eureka-server